#!/usr/bin/env bash
#
# vendor-refresh.sh
#
# Refresh vendored shared k8s modules from bnk-forge-catalog-shared.
#
# Vendored modules are pristine copies of the upstream — do not hand-edit
# them. Any AWS-specific tuning belongs in a separate wrapper module
# (e.g. modules/eks-cluster-install-flo wraps a vendored FLO submodule
# with AWS IRSA / NAD logic outside the vendored tree).
#
# Usage:
#   ./scripts/vendor-refresh.sh                  # uses default ref (release/2.2)
#   UPSTREAM_REF=release/2.3 ./scripts/vendor-refresh.sh
#   UPSTREAM_REPO=https://github.com/JLCode-tech/bnk-forge-catalog-shared.git \
#     UPSTREAM_REF=v2.3.0 ./scripts/vendor-refresh.sh
#
# Exit code 0 if vendored modules match the requested ref (with rewrites
# applied), non-zero on error. The script does not commit — that's the
# workflow's job.

set -euo pipefail

UPSTREAM_REPO="${UPSTREAM_REPO:-https://github.com/JLCode-tech/bnk-forge-catalog-shared.git}"
UPSTREAM_REF="${UPSTREAM_REF:-release/2.2}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "==> Cloning $UPSTREAM_REPO @ $UPSTREAM_REF"
git clone --depth=1 --branch "$UPSTREAM_REF" "$UPSTREAM_REPO" "$WORK_DIR/upstream" >/dev/null 2>&1

UPSTREAM_SHA="$(git -C "$WORK_DIR/upstream" rev-parse HEAD)"
echo "    Pinned commit: $UPSTREAM_SHA"

# Vendor mapping. Parallel arrays so the script works on bash 3.2 (macOS default).
# Upstream paths reflect bnk-forge-catalog-shared's modules/<name>/ layout
# (after its restructure PR — previously these were k8s/<name>/).
UPSTREAM_PATHS=(
  "modules/bnk-prerequisites"
  "modules/cert-manager"
  "modules/bnk-cert-issuer"
  "modules/install-multus"
  "modules/install-hugepages"
)
LOCAL_NAMES=(
  "eks-cluster-install-bnk-prereqs"
  "eks-cluster-install-cert-manager"
  "eks-cluster-install-cert-issuer"
  "eks-cluster-install-multus"
  "eks-cluster-install-hugepages"
)
# NOTE: eks-cluster-cneinstance-ready-gate and eks-cluster-license-activation-gate
# are cloud-specific gate modules native to THIS repo (not from catalog-shared).
# They are wired inside eks-cluster-cneinstall as TF sub-modules. Do not vendor them.

# Rewrites applied to pack.json + module.json after copy:
#   module.path: upstream-path → modules/<local>
#   dependencies.required[].module: upstream paths → modules/<local-equivalent>
#   inputs[*].from_module (module.json only): same rewrites
rewrite_jq='
def remap_dep:
  if .module == "modules/cert-manager" then .module = "modules/eks-cluster-install-cert-manager"
  elif .module == "modules/bnk-prerequisites" then .module = "modules/eks-cluster-install-bnk-prereqs"
  elif .module == "modules/bnk-cert-issuer" then .module = "modules/eks-cluster-install-cert-issuer"
  elif .module == "modules/install-multus" then .module = "modules/eks-cluster-install-multus"
  else . end;

def remap_from_module:
  if .from_module == "modules/cert-manager" then .from_module = "modules/eks-cluster-install-cert-manager"
  elif .from_module == "modules/bnk-prerequisites" then .from_module = "modules/eks-cluster-install-bnk-prereqs"
  elif .from_module == "modules/bnk-cert-issuer" then .from_module = "modules/eks-cluster-install-cert-issuer"
  elif .from_module == "modules/install-multus" then .from_module = "modules/eks-cluster-install-multus"
  else . end;

.module.path = $new_path
| (if (.module.tags // null) then .module.tags |= ((. + ["vendored","aws_eks"]) | unique) else . end)
| (if (.dependencies.required // null) then .dependencies.required |= map(remap_dep) else . end)
| (if (.dependencies.optional // null) then .dependencies.optional |= map(remap_dep) else . end)
| (if (.inputs.required // null) then .inputs.required |= map(remap_from_module) else . end)
| (if (.inputs.optional // null) then .inputs.optional |= map(remap_from_module) else . end)
'

for i in "${!UPSTREAM_PATHS[@]}"; do
  upstream_path="${UPSTREAM_PATHS[$i]}"
  local_name="${LOCAL_NAMES[$i]}"
  local_path="$REPO_ROOT/modules/$local_name"
  src="$WORK_DIR/upstream/$upstream_path"

  if [[ ! -d "$src" ]]; then
    echo "ERROR: $upstream_path not found in upstream @ $UPSTREAM_REF" >&2
    exit 1
  fi

  echo "==> Vendoring $upstream_path → modules/$local_name"
  rm -rf "$local_path"
  mkdir -p "$local_path"

  rsync -a \
    --exclude='.terraform' \
    --exclude='.terraform.lock.hcl' \
    --exclude='*.tfstate' \
    --exclude='*.tfstate.*' \
    --exclude='.DS_Store' \
    "$src/" "$local_path/"

  new_path="modules/$local_name"

  for json_file in "$local_path/bnkforge.pack.json" "$local_path/module.json"; do
    if [[ -f "$json_file" ]]; then
      tmp="$(mktemp)"
      jq --arg new_path "$new_path" "$rewrite_jq" "$json_file" > "$tmp"
      mv "$tmp" "$json_file"
    fi
  done
done

cat > "$REPO_ROOT/VENDORED.pin" <<EOF
# Auto-generated by scripts/vendor-refresh.sh — do not edit by hand.
# Override the upstream ref via the UPSTREAM_REF env var when re-running.
UPSTREAM_REPO=$UPSTREAM_REPO
UPSTREAM_REF=$UPSTREAM_REF
UPSTREAM_SHA=$UPSTREAM_SHA
REFRESHED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo ""
echo "Done. Pinned $UPSTREAM_REF (commit ${UPSTREAM_SHA:0:12})."
echo "Inspect with: git diff modules/ VENDORED.pin"
